WINDOW_SIZE = 4
MAX_SEQ_NUM = 256

HOST = "127.0.0.1"
PORT_A = 5000
PORT_B = 5001
BUFFER_SIZE = 4096

TIMEOUT = 2.0
RETRANSMIT_DELAY = 0.05

SIMULATE_LOSS = True
LOSS_RATE = 0.2

DUP_ACK_THRESHOLD = 3

INITIAL_CWND = 1
INITIAL_SSTHRESH = 8

LOG_LEVEL = "INFO"
LOG_FORMAT = "[%(asctime)s] [%(levelname)-7s] [%(name)-12s] %(message)s"
LOG_DATE_FORMAT = "%H:%M:%S"
